@startuml
interface internalPromise {
	+ Accept()
	+ Reject()
}
note left: 抽象接口

interface internalThrottle {
	- allow() (internalPromise, error)
	- doReq(req func() error, fallback func(err error) error, acceptable Acceptable) error
}
@enduml
